.TH TSSPOLICYPARAMETERS "1" "March 2024" "tsspolicyparameters 2.3" "User Commands"
.SH NAME
tsspolicyparameters \- Runs tsspolicyparameters
.SH DESCRIPTION
tsspolicyparameters
.PP
Runs TPM2_PolicyParameters
.TP
\fB\-ha\fR
policy session handle
.TP
\fB\-ph\fR
parameter hash file
.HP
\fB\-se0\fR session handle / attributes (default NULL)
.TP
01
continue
.TP
20
command decrypt
.TP
80
audit
