.TH TSSPOLICYPARAMETERS "1" "March 2024" "tsspolicyparameters 2.3" "User Commands"
.SH NAME
tsspolicyparameters \- Runs tsspolicyparameters
.SH DESCRIPTION
tsspolicyparameters
.PP
Runs TPM2_PolicyParameters
.PP
\fB\-ha\fR
policy session handle
.br
\fB\-ph\fR
parameter hash file
.HP
\fB\-se0\fR session handle / attributes (default NULL)
.br
01
continue
.br
20
command decrypt
.br
80
audit
